import { describe, it, expect } from 'vitest';
import {
  generateGcsimConfig,
  validateTeamForExport,
  generateConfigPreview,
  type GcsimExportOptions,
} from './gcsimConfigGenerator';
import type { Character, Team } from '../../../types';

// Test fixtures
const createMockCharacter = (overrides: Partial<Character> = {}): Character => ({
  id: 'char-1',
  key: 'Raiden',
  level: 90,
  ascension: 6,
  constellation: 0,
  talent: { auto: 1, skill: 9, burst: 9 },
  weapon: {
    key: 'TheCatch',
    level: 90,
    ascension: 6,
    refinement: 5,
  },
  artifacts: [
    { setKey: 'EmblemOfSeveredFate', slotKey: 'flower', level: 20, rarity: 5, mainStatKey: 'hp', substats: [{ key: 'critRate_', value: 3.9 }, { key: 'critDMG_', value: 7.8 }, { key: 'enerRech_', value: 5.8 }, { key: 'atk_', value: 5.0 }] },
    { setKey: 'EmblemOfSeveredFate', slotKey: 'plume', level: 20, rarity: 5, mainStatKey: 'atk', substats: [{ key: 'critRate_', value: 7.0 }, { key: 'critDMG_', value: 14.0 }, { key: 'enerRech_', value: 6.5 }, { key: 'hp_', value: 4.7 }] },
    { setKey: 'EmblemOfSeveredFate', slotKey: 'sands', level: 20, rarity: 5, mainStatKey: 'enerRech_', substats: [{ key: 'critRate_', value: 6.2 }, { key: 'critDMG_', value: 12.4 }, { key: 'atk_', value: 5.8 }, { key: 'hp', value: 508 }] },
    { setKey: 'EmblemOfSeveredFate', slotKey: 'goblet', level: 20, rarity: 5, mainStatKey: 'electro_dmg_', substats: [{ key: 'critRate_', value: 3.5 }, { key: 'critDMG_', value: 21.0 }, { key: 'atk_', value: 9.3 }, { key: 'enerRech_', value: 5.2 }] },
    { setKey: 'EmblemOfSeveredFate', slotKey: 'circlet', level: 20, rarity: 5, mainStatKey: 'critDMG_', substats: [{ key: 'critRate_', value: 10.5 }, { key: 'enerRech_', value: 6.5 }, { key: 'atk_', value: 14.0 }, { key: 'atk', value: 33 }] },
  ],
  notes: '',
  priority: 'main',
  teamIds: [],
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
  ...overrides,
});

const createMockTeam = (overrides: Partial<Team> = {}): Team => ({
  id: 'team-1',
  name: 'National Team',
  characterKeys: ['Raiden'],
  rotationNotes: 'Raiden E -> Bennett Q -> Xiangling Q -> Raiden Q',
  tags: ['national', 'meta'],
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
  ...overrides,
});

describe('gcsimConfigGenerator', () => {
  describe('generateGcsimConfig', () => {
    it('generates basic config for single character team', () => {
      const team = createMockTeam();
      const characters = [createMockCharacter()];

      const config = generateGcsimConfig(team, characters, { includeComments: false });

      expect(config).toContain('options iteration=1000 duration=90 swap_delay=4;');
      expect(config).toContain('target lvl=100 resist=0.1;');
      expect(config).toContain('raiden char lvl=90/90 cons=0 talent=1,9,9;');
      expect(config).toContain('raiden add weapon="catch" refine=5 lvl=90/90;');
      expect(config).toContain('raiden add set="emblem" count=4;');
      expect(config).toContain('active raiden;');
    });

    it('includes comments when requested', () => {
      const team = createMockTeam();
      const characters = [createMockCharacter()];

      const config = generateGcsimConfig(team, characters, { includeComments: true });

      expect(config).toContain('# Team: National Team');
      expect(config).toContain('# Generated by Genshin Progress Tracker');
      expect(config).toContain('# Raiden');
      expect(config).toContain('# TODO: Add rotation');
    });

    it('includes rotation notes in comments', () => {
      const team = createMockTeam({ rotationNotes: 'Test rotation notes' });
      const characters = [createMockCharacter()];

      const config = generateGcsimConfig(team, characters, { includeComments: true });

      expect(config).toContain('# Team rotation notes:');
      expect(config).toContain('# Test rotation notes');
    });

    it('respects custom options', () => {
      const team = createMockTeam();
      const characters = [createMockCharacter()];

      const options: GcsimExportOptions = {
        iterations: 5000,
        duration: 120,
        targetLevel: 95,
        targetResist: 0.15,
        swapDelay: 8,
        includeComments: false,
      };

      const config = generateGcsimConfig(team, characters, options);

      expect(config).toContain('options iteration=5000 duration=120 swap_delay=8;');
      expect(config).toContain('target lvl=95 resist=0.15;');
    });

    it('generates config for multi-character team', () => {
      const bennett = createMockCharacter({
        id: 'char-2',
        key: 'Bennett',
        weapon: { key: 'SacrificialSword', level: 90, ascension: 6, refinement: 1 },
        artifacts: [
          { setKey: 'NoblesseOblige', slotKey: 'flower', level: 20, rarity: 5, mainStatKey: 'hp', substats: [] },
          { setKey: 'NoblesseOblige', slotKey: 'plume', level: 20, rarity: 5, mainStatKey: 'atk', substats: [] },
          { setKey: 'NoblesseOblige', slotKey: 'sands', level: 20, rarity: 5, mainStatKey: 'hp_', substats: [] },
          { setKey: 'NoblesseOblige', slotKey: 'goblet', level: 20, rarity: 5, mainStatKey: 'hp_', substats: [] },
          { setKey: 'NoblesseOblige', slotKey: 'circlet', level: 20, rarity: 5, mainStatKey: 'heal_', substats: [] },
        ],
      });

      const team = createMockTeam({ characterKeys: ['Raiden', 'Bennett'] });
      const characters = [createMockCharacter(), bennett];

      const config = generateGcsimConfig(team, characters, { includeComments: false });

      expect(config).toContain('raiden char');
      expect(config).toContain('bennett char');
      expect(config).toContain('raiden add weapon="catch"');
      expect(config).toContain('bennett add weapon="sacrifical"');
      expect(config).toContain('active raiden;');
    });

    it('handles characters with 2pc+2pc artifact sets', () => {
      const character = createMockCharacter({
        artifacts: [
          { setKey: 'GladiatorsFinale', slotKey: 'flower', level: 20, rarity: 5, mainStatKey: 'hp', substats: [] },
          { setKey: 'GladiatorsFinale', slotKey: 'plume', level: 20, rarity: 5, mainStatKey: 'atk', substats: [] },
          { setKey: 'ShimenawasReminiscence', slotKey: 'sands', level: 20, rarity: 5, mainStatKey: 'atk_', substats: [] },
          { setKey: 'ShimenawasReminiscence', slotKey: 'goblet', level: 20, rarity: 5, mainStatKey: 'pyro_dmg_', substats: [] },
          { setKey: 'WanderersTroupe', slotKey: 'circlet', level: 20, rarity: 5, mainStatKey: 'critRate_', substats: [] },
        ],
      });

      const team = createMockTeam();
      const config = generateGcsimConfig(team, [character], { includeComments: false });

      expect(config).toContain('set="gladiator" count=2');
      expect(config).toContain('set="reminiscence" count=2');
      // Single piece should not appear
      expect(config).not.toContain('wanderer');
    });

    it('aggregates artifact stats correctly', () => {
      const character = createMockCharacter({
        artifacts: [
          { setKey: 'EmblemOfSeveredFate', slotKey: 'flower', level: 20, rarity: 5, mainStatKey: 'hp', substats: [{ key: 'critRate_', value: 10.0 }] },
          { setKey: 'EmblemOfSeveredFate', slotKey: 'plume', level: 20, rarity: 5, mainStatKey: 'atk', substats: [{ key: 'critDMG_', value: 20.0 }] },
          { setKey: 'EmblemOfSeveredFate', slotKey: 'sands', level: 20, rarity: 5, mainStatKey: 'enerRech_', substats: [] },
          { setKey: 'EmblemOfSeveredFate', slotKey: 'goblet', level: 20, rarity: 5, mainStatKey: 'electro_dmg_', substats: [] },
          { setKey: 'EmblemOfSeveredFate', slotKey: 'circlet', level: 20, rarity: 5, mainStatKey: 'critRate_', substats: [] },
        ],
      });

      const team = createMockTeam();
      const config = generateGcsimConfig(team, [character], { includeComments: false });

      // Check that stats line contains aggregated values
      expect(config).toContain('add stats');
      expect(config).toContain('hp=');
      expect(config).toContain('atk=');
      expect(config).toContain('cr=');
      expect(config).toContain('cd=');
    });

    it('throws error for empty team', () => {
      const team = createMockTeam({ characterKeys: [] });
      const characters: Character[] = [];

      expect(() => generateGcsimConfig(team, characters)).toThrow('No valid characters found in team');
    });

    it('handles character name variations', () => {
      const testCases = [
        { input: 'KaedeharaKazuha', expected: 'kazuha' },
        { input: 'Kazuha', expected: 'kazuha' },
        { input: 'HuTao', expected: 'hutao' },
        { input: 'RaidenShogun', expected: 'raiden' },
        { input: 'SangonomiyaKokomi', expected: 'kokomi' },
      ];

      for (const { input, expected } of testCases) {
        const character = createMockCharacter({ key: input });
        const team = createMockTeam({ characterKeys: [input] });
        const config = generateGcsimConfig(team, [character], { includeComments: false });

        expect(config).toContain(`${expected} char`);
        expect(config).toContain(`active ${expected};`);
      }
    });

    it('handles different ascension levels', () => {
      const testCases = [
        { ascension: 0, maxLevel: 20 },
        { ascension: 1, maxLevel: 40 },
        { ascension: 2, maxLevel: 50 },
        { ascension: 3, maxLevel: 60 },
        { ascension: 4, maxLevel: 70 },
        { ascension: 5, maxLevel: 80 },
        { ascension: 6, maxLevel: 90 },
      ];

      for (const { ascension, maxLevel } of testCases) {
        const character = createMockCharacter({ level: maxLevel, ascension });
        const team = createMockTeam();
        const config = generateGcsimConfig(team, [character], { includeComments: false });

        expect(config).toContain(`lvl=${maxLevel}/${maxLevel}`);
      }
    });
  });

  describe('validateTeamForExport', () => {
    it('returns valid for complete team data', () => {
      const team = createMockTeam();
      const characters = [createMockCharacter()];

      const result = validateTeamForExport(team, characters);

      expect(result.valid).toBe(true);
      expect(result.errors).toHaveLength(0);
    });

    it('returns invalid for empty team', () => {
      const team = createMockTeam({ characterKeys: [] });
      const characters: Character[] = [];

      const result = validateTeamForExport(team, characters);

      expect(result.valid).toBe(false);
      expect(result.errors).toContain('Team has no characters');
    });

    it('returns errors for missing characters', () => {
      const team = createMockTeam({ characterKeys: ['Raiden', 'MissingChar'] });
      const characters = [createMockCharacter()];

      const result = validateTeamForExport(team, characters);

      expect(result.valid).toBe(false);
      expect(result.errors).toContain('Character "MissingChar" not found in roster');
    });

    it('returns errors for characters without weapons', () => {
      const character = createMockCharacter();
      // @ts-expect-error - Testing invalid state
      character.weapon = null;

      const team = createMockTeam();
      const result = validateTeamForExport(team, [character]);

      expect(result.valid).toBe(false);
      expect(result.errors).toContain('Character "Raiden" has no weapon equipped');
    });

    it('returns errors for characters without artifacts', () => {
      const character = createMockCharacter({ artifacts: [] });
      const team = createMockTeam();

      const result = validateTeamForExport(team, [character]);

      expect(result.valid).toBe(false);
      expect(result.errors).toContain('Character "Raiden" has no artifacts equipped');
    });

    it('accumulates multiple errors', () => {
      const charWithoutWeapon = createMockCharacter({ key: 'Char1' });
      // @ts-expect-error - Testing invalid state
      charWithoutWeapon.weapon = null;

      const charWithoutArtifacts = createMockCharacter({ key: 'Char2', artifacts: [] });

      const team = createMockTeam({ characterKeys: ['Char1', 'Char2', 'MissingChar'] });
      const result = validateTeamForExport(team, [charWithoutWeapon, charWithoutArtifacts]);

      expect(result.valid).toBe(false);
      expect(result.errors.length).toBeGreaterThanOrEqual(3);
    });
  });

  describe('generateConfigPreview', () => {
    it('returns full config for short configs', () => {
      const team = createMockTeam();
      const characters = [createMockCharacter()];

      const preview = generateConfigPreview(team, characters, 100);

      expect(preview).not.toContain('truncated');
    });

    it('truncates long configs', () => {
      const team = createMockTeam();
      const characters = [createMockCharacter()];

      const preview = generateConfigPreview(team, characters, 5);

      expect(preview).toContain('... (truncated)');
      expect(preview.split('\n').length).toBeLessThanOrEqual(6); // 5 lines + truncation message
    });

    it('returns error message for invalid team', () => {
      const team = createMockTeam({ characterKeys: [] });
      const characters: Character[] = [];

      const preview = generateConfigPreview(team, characters);

      expect(preview).toContain('Error generating preview');
    });
  });

  describe('stat conversion accuracy', () => {
    it('converts substat percentages to decimals correctly', () => {
      const character = createMockCharacter({
        artifacts: [
          {
            setKey: 'EmblemOfSeveredFate',
            slotKey: 'flower',
            level: 20,
            rarity: 5,
            mainStatKey: 'hp',
            substats: [
              { key: 'critRate_', value: 31.1 }, // Should become 0.311
              { key: 'critDMG_', value: 62.2 }, // Should become 0.622
            ],
          },
          { setKey: 'EmblemOfSeveredFate', slotKey: 'plume', level: 20, rarity: 5, mainStatKey: 'atk', substats: [] },
          { setKey: 'EmblemOfSeveredFate', slotKey: 'sands', level: 20, rarity: 5, mainStatKey: 'atk_', substats: [] },
          { setKey: 'EmblemOfSeveredFate', slotKey: 'goblet', level: 20, rarity: 5, mainStatKey: 'atk_', substats: [] },
          { setKey: 'EmblemOfSeveredFate', slotKey: 'circlet', level: 20, rarity: 5, mainStatKey: 'atk_', substats: [] },
        ],
      });

      const team = createMockTeam();
      const config = generateGcsimConfig(team, [character], { includeComments: false });

      // The stats line should have decimal values for percentage stats
      // CR should be around 0.311 (from substat)
      expect(config).toMatch(/cr=0\.\d+/);
      // CD should be around 0.622 (from substat)
      expect(config).toMatch(/cd=0\.\d+/);
    });
  });
});
